<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ 
  weight: "400",
  subsets: ["latin"] 
});

export const metadata = {
  title: "Can Kara",
  description: "Hey, ich bin Can.",
>>>>>>> acf2aefa (Latest Update)
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body className={inter.className}>{children}</body>
=======
    <html lang="en" className="bg-mainbg">
      <body className={rubik.className}>{children}</body>
>>>>>>> acf2aefa (Latest Update)
    </html>
  );
}
